/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//#include <stdint.h>
//
//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif
#include <stdio.h>
#include "stm32f4xx.h"
#include "fpu.h"
#include "uart.h"
#include "timebase.h"
#include "bsp.h"
#include "adc.h"
#include "circular_buffer.h"
#include "dfplayer_lib.h"

#define GPIOAEN       (1U << 0)
#define PIN5          (1U << 6)
#define LED_PIN       PIN5

#define SENSOR_THRESH 2500

bool     btn_state;
uint32_t sensor_value;

int main(void)
{
	// Enable the FPU
	fpu_enable();

	//Initialization debug uart
	debug_uart_init();
	slave_dev_uart_init ();

	// Initialize timebase
	timebase_init();

	// Initialize the GPIO
	led_init();
	button_init();

	// Initialize the ADC
	pa1_adc_init();

	// Start ADC conversion
	start_conversion();

	// Initialize the circular buffer
	circular_buffer_init ();

	//Initialize the DF Player
	dfplayer_init(NORMAL_VOL);
	dfplayer_play_first_track();

    /* Loop forever */
	//Enable clock access to GPIOA
	RCC->AHB1ENR |= GPIOAEN;

	// Set PA5 to output mode
	GPIOA->MODER  |=  (1U << 10);
	GPIOA->MODER  &= ~(1U << 11);

	while (1){
//		GPIOA->ODR ^= LED_PIN;
//		printf("Hi \n\r");
//		delay(1);
		led_on();
		btn_state    = get_btn_state();
		sensor_value = adc_read();
		buffer_send_string("Hello\r\n",DEBUG_PORT);
		buffer_send_string("Hi\r\n",SLAVE_DEV_PORT);
		test_play_pause_btn();
		delay(1);
	}
}
